### ISSUE TITLE
Reinstall Issue

### ISSUE THREAD

**Issue by chrisfox75** [MissVeronica/um-woo-predefined-fields#2]
I had todeactivate and reactivate ultimate member due to an issue that is now working and i upgraded your plugin to the one i just downloaded from here and its now not showing me the fields to add them to the form but the form that i had the fields on the fields are working fine, how can i get the selections back to add them, they arent listed or even greyed out on the add field page like they were before, the state one you see greyed out i manually added with ACF advanced custom fields and got it transferred over to the form

Thank you Veronics, help is appreciated

Chris Fox
![Edit Form “Raffle Registration” ‹ Max Tactical Firearms — WordPress — Mozilla Firefox 2_2_2024 3_29_39 PM](https://github.com/MissVeronica/um-woo-predefined-fields/assets/31097852/5c20df99-e48d-4b16-9f26-1d16ba6621d4)

**Comment by MissVeronica** [comment]
The issue is when WooCommerce is deactivated.
Change line 18 to a comment
//if ( ! class_exists( 'WC' ) ) return;
I have updated the plugin with this commented line

**Comment by chrisfox75** [comment]
Update and rezip the script and reinstall the script??

**Comment by MissVeronica** [comment]
You can download the plugin zip file and reinstall from github

**Comment by chrisfox75** [comment]
So i need to change the line in the php file and reinstall, i just want to make sure i install it right

Thank you!

**Comment by MissVeronica** [comment]
Current ZIP download is updated and should work without edit

**Comment by chrisfox75** [comment]
Thank you!!

**Comment by chrisfox75** [comment]
Just installed, it crashed the site, said 

In this case, WordPress caught an error with one of your plugins, Ultimate Member – Woo Predefined Fields.

I had to manually remove the plugin


Error Details
=============
An error of type E_ERROR was caused in line 275 of the file /home2/maxtacticalfirea/public_html/wp-content/plugins/um-woo-predefined-fields-main/um-woo-predefined-fields.php. Error message: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /home2/maxtacticalfirea/public_html/wp-content/plugins/um-woo-predefined-fields-main/um-woo-predefined-fields.php:275
Stack trace:
#0 /home2/maxtacticalfirea/public_html/wp-includes/class-wp-hook.php(324): UM_WOO_Predefined_Fields->um_settings_structure_predefined_fields_woo()
#1 /home2/maxtacticalfirea/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /home2/maxtacticalfirea/public_html/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-settings.php(1095): apply_filters()
#3 /home2/maxtacticalfirea/public_html/wp-includes/class-wp-hook.php(324): um\admin\core\Admin_Settings->init_variables()
#4 /home2/maxtacticalfirea/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /home2/maxtacticalfirea/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /home2/maxtacticalfirea/public_html/wp-admin/admin.php(175): do_action()
#7 /home2/maxtacticalfirea/public_html/wp-admin/edit.php(10): require_once(‘/home2/maxtacti…’)
#8 {main}
thrown

**Comment by MissVeronica** [comment]
Thanks for the detailed issue report.
This issue has been fixed now in version 2.3.4
